### ISSUE TITLE
Promises aren't removed from store when trashed

### ISSUE THREAD

**Issue by glasser** [hjylewis/trashable-react#2]
I'm not super clear if this causes any end-to-end issues or memory leaks, but most likely when you trash the promises on cWU, the removePromise calls won't get invoked, so they will stay in the store.

Might make sense to make handledPromise.trash a function that calls trashablePromise.trash and then removes the promise. Or maybe make cWU clear the store, though that's sort of the wrong level to do it at.

**Comment by hjylewis** [comment]
If cWU is called, the store will be trashed anyway because the entire object is dereferenced.

But if a user manually trashes the `handledPromise` (what is returned from `registerPromise`) before cWU, you're right, `removePromise` isn't called. This is potentially a memory leak if a user is registering a ton of promises. Trashing them will not free up any memory, only unmounting the entire component will do that.

In that case, your solution would work, wrap up the `trash` method in a function that also calls `removePromise`.
